{ config, lib, ... }:
{
  imports = [
    ./1password.nix
    ./bat.nix
    ./charm.nix
    ./claude-code.nix
    ./cursor.nix
    ./direnv.nix
    ./docker.nix
    ./colima.nix
    ./drawio.nix
    ./editorconfig.nix
    ./eza.nix
    ./fd.nix
    ./fonts.nix
    ./fzf.nix
    ./gh
    ./ghostty
    ./git
    ./glow.nix
    ./gnused.nix
    ./gpg
    ./grep.nix
    ./helix
    ./languages
    ./mdbook.nix
    ./nh.nix
    ./nurl.nix
    ./obsidian.nix
    ./pandoc
    ./postgre.nix
    ./ripgrep.nix
    ./sops
    ./starship
    ./taskwarrior.nix
    ./wezterm
    ./yazi
    ./zoxide.nix
    ./zsh.nix
  ];
}
