keys:
  # System Host Keys
  - &host_rhesus age:age1e0fkkg5mqfuw2l33jycze2m9qepw6as8ag2n09va47vejmr75pcqk3zcx5 # Replace with your actual age public key
  - &host_mulatta age:age1e0fkkg5mqfuw2l33jycze2m9qepw6as8ag2n09va47vejmr75pcqk3zcx5 # Replace with your actual age public key
  # User Keys
  - &user_seungwon age:age1e0fkkg5mqfuw2l33jycze2m9qepw6as8ag2n09va47vejmr75pcqk3zcx5 # Replace with your actual age public key

creation_rules:
  # Common secrets for all hosts
  - path_regex: hosts/common/secrets.yaml
    key_groups:
    - age:
      - *host_rhesus
      - *host_mulatta
      - *user_seungwon
      
  # Host-specific secrets
  - path_regex: hosts/[^/]+/secrets.yaml
    key_groups:
    - age:
      - *host_rhesus
      - *host_mulatta
      - *user_seungwon 