keys:
  # User
  - &users:
    - &seungwon age1yubikey1qwfc6u8qwt0c4a96uaycy3e4wewgyzvt9ttlapfl88cfa98s4tx0kznpk44
  # Host
  - &hosts:
    - &rhesus age1uwak6mptuthu2rgz9vgkvpv5cuqgqav6e6j00vevx5tsnrsr69zswk4j99
    - &mulatta age1s87glrf9qv43qsem30gyupcttsjwkta9fuz2y7ygz2u4vxyfhvesjxd5hj

creation_rules:
  # ==== Common Secrets ====
  - path_regex: hosts/common/secrets.yaml
    key_groups:
    - age:
      - *seungwon    
      - *mulatta
      - *rhesus
