exclude_paths:
  - "**/.git/**"
  - "**/node_modules/**"
  - "**/.terraform/**"
  - "**/.direnv/**"
  - "**/result*"
  - "**/.gcroots/**"
  - "**/*.age"
  - "**/*.gpg"
  - "**/examples/**"
  - "**/tests/**"
  - "**/docs/**"

include_paths:
  - "**/*.nix"
  - "**/secrets*.yaml"
  - "**/secrets*.yml"
  - "**/.env"
  - "**/*.key"
  - "**/configuration.nix"
  - "**/hardware-configuration.nix"
  - "**/flake.nix"
  - "**/flake.lock"

# Disable Specific Detector (in case detecting too much false positive)
exclude_detectors:
  - "Generic"

# Enable Custom Detector (NixOS Specialized)
detectors:
  - name: "nixos-hardcoded-password"
    keywords:
      - "password"
      - "initialPassword"
    regex:
      nixos_password: 'password\s*=\s*"([^"]{8,})"'
    verify: false
    
  - name: "nixos-secret-key"
    keywords:
      - "secretKey"
      - "privateKey"
      - "apiKey"
    regex:
      secret_key: '(secretKey|privateKey|apiKey)\s*=\s*"([^"]{16,})"'
    verify: false

  - name: "ssh-private-key"
    keywords:
      - "BEGIN PRIVATE KEY"
      - "BEGIN RSA PRIVATE KEY"
      - "BEGIN OPENSSH PRIVATE KEY"
    regex:
      ssh_key: '-----BEGIN [A-Z ]*PRIVATE KEY-----[\s\S]*?-----END [A-Z ]*PRIVATE KEY-----'
    verify: false

# Global config
entropy_threshold: 3.0
max_target_megabytes: 100
concurrency: 8

# Filter Scan Result
only_verified: false
filter_unverified: true
