add_newline = false
format = """$directory$character"""
right_format = """$all"""
command_timeout = 5000

[character]
success_symbol = '[❯](bold green)'
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"

[git_branch]
style = "bold purple"
format = '[$symbol$remote_name]($style) '
truncation_length = 4
truncation_symbol = "…"
ignore_branches = ['master', 'main']

[git_commit]
disabled = true

[nix_shell]
disabled = false
format = "[$symbol( \\($name\\))]($style) "
symbol = "❄️"
style = "bold blue"

[pixi]
format = "[$symbol($version )(\\($environment\\) )]($style)"

[python]
symbol = "🐍"
format = "[${symbol}${pyenv_prefix}(${version})]($style) "

[rust]
format = "[$symbol($version )]($style) "
symbol = "🦀 "

[typst]
format = "[$symbol]($style) "
style = "bold #0093A7"

[package]
format = '[$symbol$version]($style) '

[cmd_duration]
min_time = 500
format = "[$duration]($style) "
style = "dimmed white"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
