name: Security - Secret Detection
on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'
jobs:
  secret-detection:
    name: Scan for Secrets in NixOS Config
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog@v3.88.35
        with:
          extra_args: >-
            --results=verified,unknown
            --json
            --config=.trufflehog.yaml
